spring:
  datasource:
    password: root
    username: root
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://localhost/moma?serverTimezone=UTC
  http:
    encoding:
      charset: UTF-8
      force: true
      enabled: true
  redis:
    host: localhost

mybatis:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    aggressive-lazy-loading: true


wechat:
  appid: wxedcd71ddcc04678b
  login-url: https://api.weixin.qq.com/sns/jscode2session?appid=%s&secret=%s&js_code=%s&grant_type=authorization_code
  app-secret: de6a35eaa96cbae7f3cf28b67418045e
  token-live-time: 600
#debug: true