spring:
  datasource:
    password: root
    username: root
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://192.168.0.107/moma
  http:
    encoding:
      charset: UTF-8
      force: true
      enabled: true
  redis:
    host: 192.168.0.107

mybatis:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    aggressive-lazy-loading: true
